### ISSUE TITLE
NBE-03 - Contract with Maximum Duration `[Low]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/bridge-evm-contracts#50]
<p>The logic related to <code>deposits</code> and <code>withdrawals</code> requires having certain values ​​correctly signed according to the <code>depositNonce</code> and <code>withdrawalNonce</code> variables, which are incremental, of type <code>uint64</code>. However, no logic has been established to account for the scenario in which these values ​​reach their maximum value, which would currently trigger a denial of service.</p><p>Although it is true that these values ​​are large enough to extend over time, it is advisable to review this logic in order to make the contract resilient to the passage of time, or possible attacks with the aim of increasing the nonce in the future.</p>

**Remediation:**
<ul><li><p>Establish a logic that considers the end of the type used for <code>nonce</code> fields.</p></li></ul>

**Source references:**
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L31-L32">https://github.com/bane-labs/bridge-evm-contracts/blob/14cd3efd3f618fd18a4cda358c791fdca0e66cff/contracts/BridgeContract.sol#L31-L32</a></p>

**Comment by roman-khimov** [comment]
N3 will run out of `uint32` blocks earlier than that!

**Comment by shargon** [comment]
> N3 will run out of `uint32` blocks earlier than that!

Blocks have version and this contract is not upgradeable, this issue can be solved with `unchecked`.

**Comment by mialbu** [comment]
Just to keep my thoughts written down here...

Actually, now with the latest EVM contracts and the way the bridge states are stored (see below), the nonces require a full slot in the Neo X contract storage. Afaik, this means that it's possible to upgrade the contract and use nonces of type up to `uint256` (i.e., one full slot size). Ofc if this were to be done in the future, it'd need to be aligned with upgrading the N3 contract at the same nonce (the same height of the bridge hash chain) to remain the same root.

https://github.com/bane-labs/bridge-evm-contracts/blob/1fc995f9c158a9948d5c2008db9773c9c81b2bfd/contracts/BridgeStorage.sol#L15-L18

The `gasBridge` is split into storage slots as follows (numbering relative to previous slot allocations):
- slot#1 depositState.nonce
- slot#2 depositState.root
- slot#3 withdrawalState.nonce
- slot#4 withdrawalState.root

So, because the roots require full slots (i.e., are of size >24 bytes), the nonces are stored in a full slot without any additional data there anyway.

One could argue that it'd make sense to just go with uint256... We can consider that, but need to discuss this internally.

**Comment by mialbu** [comment]
>Although it is true that these values ​​are large enough to extend over time [...] possible attacks with the aim of increasing the nonce in the future.

Is this what you had in mind with this statement, @shargon ?

**Comment by shargon** [comment]
With upgradability the issue have 0 risk, for me it's almost solved

**Comment by mialbu** [comment]
The nonces have been changed to a uint256. I'll mark this issue as resolved.
