### ISSUE TITLE
NBE-04 - Wrong verifyDepositsAndTransfer Logic `[Low]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/bridge-evm-contracts#51]
<p>The <code>verifyDepositsAndTransfer</code> method of the <code>BridgeContract</code> contract incorrectly performs the implemented logic according to whether or not the address is a contract. Currently, it appears that when it is not a contract it tries to use the <code>call</code> method, and if it fails it creates the corresponding claim. However, when it is an address, this call will never fail, which leads us to suspect that this condition is inverted with respect to the desired logic.</p>

![image](https://github.com/bane-labs/bridge-evm-contracts/assets/3167973/2e4a8013-d13b-472c-9795-49f399e991e9)

<p>This issue could not be confirmed due to the lack of project documentation. It is advisable for the development team to conduct thorough research into the matter.</p>

**Remediation:**
<ul><li><p>Modify the mentioned condition by eliminating the <code>!</code>.</p></li></ul>

```
if (isContract(to)) { ... }
```

**Comment by mialbu** [comment]
Based on the tests I've written, the boolean value `success` that is returned from `to.call{value: sendValue}("")` is `false` if e.g., the contract has insufficient funds. Afaik, insufficient funds should be the only case this happens.

Take a look at [this commit](4a3804e) where I've added another test for exactly this (besides a simpler test existing already some lines above).

Based on the decision in #37 we'll either need to cover this case or not. There are two options:
1. the bridge contract (the bridge's proxy) holds all the initial gas allocation, OR
2. there's a treasury holding all the initial gas allocation, and it'll be used to fund the bridge contract (the bridge's proxy) from time to time.

In case 1, the check in question will be redundant, since as you've said this case will never happen.
In case 2, the check is needed and the logic as is makes sense. It would become a possibility that the contract has insufficient funds if it's not funded enough.

For case 2 take a look at the added test in [the commit mentioned above already](4a3804e). It covers a scenario where there's a big deposit that cannot be executed due to insufficient funds. However, with the current logic, the bridge process could go on for smaller deposit amounts.

**Comment by mialbu** [comment]
Regardless of the functionality I think it makes sense to cover the contract case first. I'll invert the `if...else` to increase readability. Done in d0f07e95ed6f3082701de5fd8364970673dff75b.

**Comment by shargon** [comment]
The thing is: when it's a contract, you want to force them to claim? or try to send it first?

**Comment by mialbu** [comment]
> The thing is: when it's a contract, you want to force them to claim? or try to send it first?

Force them to claim. The relayer should not need to pay for unknown gas usage on the receiving contract. Also, the behaviour of the receiving contract is not known.

The automatic execution is only supported for EOAs. If you'd like to send funds to a contract on the destination chain, you can either:
- bridge to an EOA and then send it yourself in a separate transaction, or
- send it to a contract address, it will end up to be claimable. And then you can issue a separate transaction claiming it (i.e., sending it to the specified contract) and pay for the complete execution cost yourself.

**Comment by mialbu** [comment]
> However, when it is an address, this call will never fail

@shargon, this would change with the introduction of a treasury (see https://github.com/bane-labs/go-ethereum/issues/183). If Neo X will use a treasury to fund the bridge from time to time instead of the bridge holding all the initial allocation, this call **can** actually fail in case of insufficient funds held in the bridge contract. In that case, the deposit should be added to the claimable mapping.

**Comment by mialbu** [comment]
Do you know of any other scenario this call to send funds to an EOA would fail, if not for insufficient funds?

**Comment by shargon** [comment]
> Force them to claim. 

Then this issue can be closed.

> Do you know of any other scenario this call to send funds to an EOA would fail, if not for insufficient funds?

I think that is not possible.

**Comment by mialbu** [comment]
> > Force them to claim.
> 
> Then this issue can be closed.
> 
> > Do you know of any other scenario this call to send funds to an EOA would fail, if not for insufficient funds?
> 
> I think that is not possible.

I'll close this based on this comment
