### ISSUE TITLE
NBE-09 - Lack of Documentation `[Informative]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/bridge-evm-contracts#56]
<p>Despite having excellent coverage of the project, it is curious to observe that it lacks documentation. Having updated and accurate documentation of the project is an essential aspect for open source projects, in fact it is closely related to the adoption and contribution of the project by the community.</p><p>Documentation is an integral part of the Secure Software Development Life Cycle (SSDLC), and it helps to improve the quality of the project. Therefore, it is recommended to add the code documentation with the according descriptions of the functionalities, classes and public methods.</p>

**References:**
- https://snyk.io/learn/secure-sdlc/
- https://www.freecodecamp.org/news/why-documentation-matters-and-why-you-should-include-it-in-your-code-41ef62dd5c2f

**Comment by mialbu** [comment]
I'll close this issue as imo the documentation efforts have improved since this issue was opened. The external documentation was extended and updated, while a lot more functions in the code base have now documentation and several unit tests have been added which also help to clarify the desired behavior of the implementation.
